services:
  - type: web
    name: krishisaathi-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATA_GOV_IN_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: WEATHER_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///./krishisaathi.db
      - key: FIREBASE_CREDENTIALS_PATH
        sync: false
